### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by LesterKim** [spaceandtimelabs/SxT-Go-SDK#7]
We should add automated tests for the key parts of this SDK. Currently, there are none. A very simple way would be to translate [the Python test cases](https://github.com/spaceandtimelabs/SxT-Python-SDK/tree/main/tests). Note: The Node.js SDK does not have tests. We can then add a CI GitHub workflow for each PR and merge to main.

**Comment by chilaraiSxt** [comment]
Yes definitely. I'll plan to add a few test cases

**Comment by chilaraiSxt** [comment]
PR #12 contains some basic test cases for this repo
